/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkVoraRouteImport } from './routes/work.vora'
import { Route as WorkShiftflowRouteImport } from './routes/work.shiftflow'
import { Route as WorkQntraRouteImport } from './routes/work.qntra'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkVoraRoute = WorkVoraRouteImport.update({
  id: '/work/vora',
  path: '/work/vora',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkShiftflowRoute = WorkShiftflowRouteImport.update({
  id: '/work/shiftflow',
  path: '/work/shiftflow',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkQntraRoute = WorkQntraRouteImport.update({
  id: '/work/qntra',
  path: '/work/qntra',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/qntra': typeof WorkQntraRoute
  '/work/shiftflow': typeof WorkShiftflowRoute
  '/work/vora': typeof WorkVoraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/qntra': typeof WorkQntraRoute
  '/work/shiftflow': typeof WorkShiftflowRoute
  '/work/vora': typeof WorkVoraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/qntra': typeof WorkQntraRoute
  '/work/shiftflow': typeof WorkShiftflowRoute
  '/work/vora': typeof WorkVoraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work/qntra' | '/work/shiftflow' | '/work/vora'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work/qntra' | '/work/shiftflow' | '/work/vora'
  id: '__root__' | '/' | '/work/qntra' | '/work/shiftflow' | '/work/vora'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkQntraRoute: typeof WorkQntraRoute
  WorkShiftflowRoute: typeof WorkShiftflowRoute
  WorkVoraRoute: typeof WorkVoraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/vora': {
      id: '/work/vora'
      path: '/work/vora'
      fullPath: '/work/vora'
      preLoaderRoute: typeof WorkVoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/shiftflow': {
      id: '/work/shiftflow'
      path: '/work/shiftflow'
      fullPath: '/work/shiftflow'
      preLoaderRoute: typeof WorkShiftflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/qntra': {
      id: '/work/qntra'
      path: '/work/qntra'
      fullPath: '/work/qntra'
      preLoaderRoute: typeof WorkQntraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkQntraRoute: WorkQntraRoute,
  WorkShiftflowRoute: WorkShiftflowRoute,
  WorkVoraRoute: WorkVoraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
